# permissions for end users to view chucknorris.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chucknorris-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chucknorrisjoke-controller
    app.kubernetes.io/part-of: chucknorrisjoke-controller
    app.kubernetes.io/managed-by: kustomize
  name: chucknorris-viewer-role
rules:
- apiGroups:
  - jokes.example.com
  resources:
  - chucknorris
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jokes.example.com
  resources:
  - chucknorris/status
  verbs:
  - get
